# Generated by Django 4.1.2 on 2022-10-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chairman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairman',
            options={'verbose_name_plural': '1. Chairman'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '4. Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '3. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '2. Teacher'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='intereseted_categories',
            new_name='interested_categories',
        ),
    ]
