# Generated by Django 4.1.2 on 2022-11-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_exam_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interested_categories',
        ),
    ]
