# Generated by Django 4.1.2 on 2022-11-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='chair_imgs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='student_imgs/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='teacher_imgs/'),
        ),
    ]
