# Generated by Django 4.1.2 on 2022-11-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_chairman_profile_img_student_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
