# Generated by Django 4.1.2 on 2022-11-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_courseexam_options_remove_courseexam_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseexam',
            options={'verbose_name_plural': '11. Course exam'},
        ),
        migrations.RemoveField(
            model_name='courseexam',
            name='question',
        ),
        migrations.RemoveField(
            model_name='courseexam',
            name='student',
        ),
        migrations.AddField(
            model_name='courseexam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='courseexam',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
        ),
        migrations.AddField(
            model_name='courseexam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.CreateModel(
            name='AttemptExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_ans', models.CharField(max_length=200, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examquestions')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'verbose_name_plural': '11. Attempted Questions',
            },
        ),
    ]
