# Generated by Django 4.1.2 on 2022-11-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_courseexam_options_remove_courseexam_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptexam',
            options={'verbose_name_plural': '12. Attempted Questions'},
        ),
    ]
