# Generated by Django 4.1.5 on 2023-01-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_course_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name_plural': 'Exams'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examss', to='main.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='number_of_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.IntegerField(help_text='duration of the exam(in mins.)', null=True),
        ),
    ]
